services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    ports:
      - 8080:8080

  nginx-server:
    image: nginx-server
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - nextjs
    
