services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    container_name: nextjs
    networks:
      - tokena-net

  nginx-server:
    image: nginx-server
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - nextjs
    networks:
      - tokena-net

networks:
  tokena-net:
    driver: bridge